### ISSUE TITLE
Syntax Error reported for social-network tutorial. 

### ISSUE THREAD

**Issue by topherconley** [graknlabs/console#121]
I was attempting to follow your tutorial with the  [social network schema](https://docs.grakn.ai/docs/files/social-network/schema.gql) using grakn-server/console version 2.0.0-alpha-4. The following command reports a syntax error, which I found rather perplexing after looking at the docs and the reported line 71. 

```sh
social-network::schema::write> source /Users/conley/scratch/grakn-core/schema/social-network-schema.gql
```

> [GQL03] Graql Error: There is a syntax error at line 71:
> 		plays spoken,
>         ^
> no viable alternative at input 'spoken'
> [GQL03] Graql Error: There is a syntax error at line 71:
> 		plays spoken,
>         ^
> mismatched input 'spoken' expecting {'match', 'define', 'undefine', 'insert', 'compute'}

Is this simply an incompatibility between the latest version and older versions when the tutorial was developed? 
Thanks in advance, 
Chris Conley

**Comment by haikalpribadi** [comment]
Hi, @topherconley, the error message above is saying, at line 71:
```
no viable alternative at input 'spoken' 
```

Which mean `spoken` is not expected, and thus wrong, at line 71. Indeed, that token is actually wrong, because you now need to refer to roles by their "scope", such as `marriage:spouse`. This was described in the release notes at section 3: https://github.com/graknlabs/graql/releases/tag/2.0.0-alpha

However, most importantly, I believe you are visiting the wrong documentation website. The schema above seems to be linked from https://docs.grakn.ai, meanwhile Grakn 2.0.0-alpha is only live stage docs website at https://dev.docs.grakn.ai - I apologise for the subtle difference, we tried to emphasise this not in the release notes too: https://discuss.grakn.ai/t/grakn-2-0-alpha-best-practices-in-distributed-systems-and-computer-science/2307

Let me know if all that helps. I shall close this issue for now. Thanks, @topherconley !

**Comment by topherconley** [comment]
Thanks @haikalpribadi this is exactly what I needed. I am excited to get started.
